path: multirun/2023-07-27/10-33-58 #multirun/2023-07-18/10-50-09
reset_path: true

# post_process:
#     _target_: evaluation.utils.evaluation_log_utils.post_process
#     _partial_: true

eval_multirun_agents:
    # "Marta Rodriguez":
    #     how_to_help:
    #         _target_: evaluation.eval_multirun_agents.reflect_response.reflect_response
    #         _partial_: true
    #         initial_question: “Do you know what is causing your pain?”.
    "Aaliyah Williams":
        how_to_help:
            _target_: evaluation.eval_multirun_agents.reflect_interview.reflect_interview
            _partial_: true
            questions:
                - "Based on your recollection, do you know how Marta Rodriguez is doing?"
                - "Do you know how you may be able to help her? Be specific."
    "Ravi Patel":
        how_to_help:
            _target_: evaluation.eval_multirun_agents.reflect_interview.reflect_interview
            _partial_: true
            questions:
                - "Based on your recollection, do you know how Marta Rodriguez is doing?"
                - “Can you diagnose it?"
                - "How can you treat it?"
