defaults:
    - memory_prompts: default_memory_prompts.yaml
    - _self_

_target_: lyfe_agent.ThreeStageMemoryManager
_partial_: true
memory_modules:
    workmem:
        # _target_: lyfe_agent.MemoryStore
        # _partial_: true
        capacity: 4
        metadata_types:
            - generic
            - visual
            - audio
            - spacial
            - mental
    recentmem:
        # _target_: lyfe_agent.EmbeddingMemory
        # _partial_: true
        capacity: 10
        num_memories_retrieved: 1
        forgetting_algorithm: True
        forgetting_threshold: 0.9
        # tick_limit: 1 # how frequently to update the memory
    longmem:
        # _target_: lyfe_agent.EmbeddingMemory
        # _partial_: true
        capacity: 10_000
        num_memories_retrieved: 3
        forgetting_algorithm: True
        forgetting_threshold: 0.9
    # TEMPORARY
    obsbuffer:
        # _target_: lyfe_agent.ObsBuffer
        # _partial_: true
        capacity: 6
    
db_scan_eps: 0.5
tick_limit: 1 # how frequently to update the recentmem
